[plugin]
id = "com.jacobtread.tilepad.vtstudio"
name = "VTube Studio"
version = "0.0.1"
authors = ["Jacobtread"]
description = "Tilepad VTube studio actions"

[category]
label = "VT Studio"
icon = "images/vtstudio.png"

[actions.trigger_hotkey]
label = "Trigger Hotkey"
icon = "images/shortcut.svg"
description = "Trigger a VTStudio hotkey"
inspector = "ui/connect.html"

[actions.switch_model]
label = "Switch Model"
icon = "images/switch-user.svg"
description = "Switch the current VTStudio model"
inspector = "ui/connect.html"
